# Generated by Django 6.0.6 on 2026-06-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fruit',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
